#!/usr/bin/bash
# https://github.com/ssbostan/devops-bash-scripts


function-print-italic-string(){
    while true; do 
    if [[ $# -eq 0 ]]; then 
        break
    fi
        echo -en "\e[3m$1\e[0m "
        shift 1 
    done
    
}
