#!/usr/bin/bash

# https://github.com/ssbostan/devops-bash-scripts


get-directory-size() {
du -s -k $1 | awk '{print "The total size of",$2,"directory is",$1/1024, "MB"}'
}

instruction() {
    cat <<EOL
How to use this command: $0 <directory_name or path>

EOL
}

if [[ $# -ne 1 ]]; then
    instruction
    exit 1
fi

if [[ ! -d "$1" ]]; then
    echo "ERROR: $1 should be a directory."
    exit 1
fi

get-directory-size()

