#!/bin/bash
ACTION=none
DATABASE=default.db

usage() {
	cat <<EOL
Usage: filechecker <init|scan> [OPTIONS] <source_dir>
Options:
	--dbname <database>: Database file.
		
EOL
}

if [[ $# -lt 1 ]]; then
	usage
	exit 1
fi

case $1 in
init)
	ACTION=init
	shift 1
	;;

scan)
	ACTION=scan
	shift 1
	;;
*)
	echo "Error: Undefined action."
	exit 1
	;;
esac

while true; do
	case $1 in
	--dbname)
		DATABASE=$2
		shift 2
		;;

	*)
		break
		;;
	esac
done

case $ACTION in
init)
	if [[ $# -ne 1 ]]; then
		usage
		exit 1
	fi
	if [[ ! -d $1 ]]; then
		echo "Error: $1 should be a directory."
		exit 1
	fi

	FILES=($(tree -iRfan --noreport $1 | grep -Ev "\->/error openning dir"))
	for file in ${FILES[@]}; do
		FILE_CHACKSUM=($(md5sum $file 2>/dev/null))
		if [[ $? -eq 0 ]]; then
			echo "${FILE_CHACKSUM[0]} ${FILE_CHACKSUM[1]}" >>$DATABASE
		fi
	done
	;;

scan)
	DB_ARRAY=($(cat ./default.db))
	LENGTH="${#DB_ARRAY[@]}"
	for i in $(eval echo {0..$(($LENGTH - 1))..2}); do
		NEW_MD5=($(md5sum ${DB_ARRAY[i + 1]}))
		if [[ "${NEW_MD5[0]}" != "${DB_ARRAY[i]}" ]]; then
			echo "${DB_ARRAY[i + 1]} is changed"
		fi
	done
	;;

*)
	echo "Error: Undefined action."
	;;

esac
